// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhcyR3VwppnLYsgOF_f3_RG68OZTAX9A',
    appId: '1:493696613453:web:cd9140c49073f9f866b004',
    messagingSenderId: '493696613453',
    projectId: 'mastermindauth',
    authDomain: 'mastermindauth.firebaseapp.com',
    storageBucket: 'mastermindauth.firebasestorage.app',
    measurementId: 'G-7TLP8RBV3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLaeFZ_STkKIpI5L-hjmqJXqTGgci_vdY',
    appId: '1:493696613453:android:b835598495b5439866b004',
    messagingSenderId: '493696613453',
    projectId: 'mastermindauth',
    storageBucket: 'mastermindauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB294OIwtbm60ou7deBml7ZPVGuHOIWf_w',
    appId: '1:493696613453:ios:d50312f91eb33e7266b004',
    messagingSenderId: '493696613453',
    projectId: 'mastermindauth',
    storageBucket: 'mastermindauth.firebasestorage.app',
    iosBundleId: 'com.example.emmFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB294OIwtbm60ou7deBml7ZPVGuHOIWf_w',
    appId: '1:493696613453:ios:d50312f91eb33e7266b004',
    messagingSenderId: '493696613453',
    projectId: 'mastermindauth',
    storageBucket: 'mastermindauth.firebasestorage.app',
    iosBundleId: 'com.example.emmFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdhcyR3VwppnLYsgOF_f3_RG68OZTAX9A',
    appId: '1:493696613453:web:4a6eba95c958ff5a66b004',
    messagingSenderId: '493696613453',
    projectId: 'mastermindauth',
    authDomain: 'mastermindauth.firebaseapp.com',
    storageBucket: 'mastermindauth.firebasestorage.app',
    measurementId: 'G-JG47TXHB5T',
  );
}
